//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EncryptAlgorithm.rc
//
#define IDR_MANIFEST_XPSTYLE            1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DIALOG_MAIN                 102
#define IDD_DIALOG_SYMMETRYDES          103
#define IDD_DIALOG_SYMMETRY             104
#define IDR_MAINFRAME                   128
#define IDI_ICON_FOLDER                 130
#define IDC_URL_ABOUTBOX_LINK           1000
#define IDC_URL_ABOUTBOX_BLOGLINK       1001
#define IDC_BUTTON_MAIN_CLEARPLAINTEXT  1100
#define IDC_BUTTON_MAIN_CLEARCIPHERTEXT 1101
#define IDC_BUTTON_MAIN_CLEARALLTEXT    1102
#define IDC_BUTTON_MAIN_ABOUT           1103
#define IDC_BUTTON_MAIN_ENCRYPT         1104
#define IDC_BUTTON_MAIN_DECRYPT         1105
#define IDC_TAB_MAIN_ENCRYPTALGORITHM   1106
#define IDC_EDIT_MAIN_CIPHERTEXT        1107
#define IDC_EDIT_MAIN_PLAINTEXT         1108
#define IDC_EDIT_MAIN_SOURCEFILE        1109
#define IDC_EDIT_MAIN_SOURCEFOLDER      1110
#define IDC_EDIT_MAIN_OUTPUTFOLDER      1111
#define IDC_RADIO_MAIN_ENCRYPTTEXT      1112
#define IDC_RADIO_MAIN_ENCRYPTFILE      1113
#define IDC_RADIO_MAIN_HEX              1114
#define IDC_RADIO_MAIN_BINARY           1115
#define IDC_RADIO_MAIN_ORIGINALCHARACTER 1116
#define IDC_RADIO_MAIN_KEEPSOURCEFILE   1117
#define IDC_RADIO_MAIN_REPLACESOURCEFILE 1118
#define IDC_RADIO_MAIN_ENCRYPTSINGLEFILE 1119
#define IDC_RADIO_MAIN_ENCRYPTFOLDER    1120
#define IDC_STATIC_MAIN_SOURCEFILE      1121
#define IDC_STATIC_MAIN_SOURCEFOLDER    1122
#define IDC_STATIC_MAIN_OUTPUTFOLDER    1123
#define IDC_STATIC_MAIN_ENCRYPTDECRYPT  1124
#define IDC_RADIO_MAIN_OCTAL            1125
#define IDC_RADIO_MAIN_BINARY4          1126
#define IDC_RADIO_SYMMETRYDES_DES       1200
#define IDC_RADIO_SYMMETRYDES_3DES      1201
#define IDC_RADIO_SYMMETRYDES_DESECB    1203
#define IDC_RADIO_SYMMETRYDES_DESCBC    1204
#define IDC_RADIO_SYMMETRYDES_DESCFB    1205
#define IDC_RADIO_SYMMETRYDES_DESOFB    1206
#define IDC_RADIO_SYMMETRYDES_DESCTR    1207
#define IDC_EDIT_SYMMETRYDES_INITIALVALUE 1208
#define IDC_EDIT_SYMMETRYDES_CIPHERKEY 1209
#define IDC_STATIC_SYMMETRYDES_INITIALVALUE 1210
#define IDC_TAB_SYMMETRY_ENCRYPTALGORITHM 1300

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2401
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
